name: solar-system-workflow
on:
  push:
    branches:
        - main
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:
  login:
    name: login
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: docker login
          uses: docker/login-action@v2
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    name: docker-build
    runs-on: ubuntu-latest
    needs: login   
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/app:latest
            ${{ vars.DOCKERHUB_USERNAME }}/app:${{ github.sha }}
  test:
    name: docker-test
    runs-on: ubuntu-latest
    needs: build   
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: test images
        run: |
            docker images
            docker run --name app -d \
            -p 3000:3000 \
            -e MONGO_URI=$MONGO_URI \
            -e MONGO_USERNAME=$MONGO_USERNAME \
            -e MONGO_PASSWORD=$MONGO_PASSWORD \
            ${{ vars.DOCKERHUB_USERNAME }}/app:${{ github.sha }}
            export IP_ADDRESS=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'app)
            echo $IP
            echo Testing image URL using wget
            wget -q -O - 127.0.0.1:3000/live | grep live

  push:
    name: docker-push
    runs-on: ubuntu-latest
    needs: test   
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/app:latest
            ${{ vars.DOCKERHUB_USERNAME }}/app:${{ github.sha }}

