name: solar-system-workflow
on:
  push:
    branches:
        - main
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: setup build
        uses: docker/setup-buildx-action@v3
    
      - name: Build and push image (commit tag only)
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/app:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: setup build
        uses: docker/setup-buildx-action@v3
      
      - name: Pull and test image
        run: |
          docker pull ${{ vars.DOCKERHUB_USERNAME }}/app:${{ github.sha }}
          docker run --name app -d \
          -p 3000:3000 \
          -e MONGO_URI=$MONGO_URI \
          -e MONGO_USERNAME=$MONGO_USERNAME \
          -e MONGO_PASSWORD=$MONGO_PASSWORD \
          ${{ vars.DOCKERHUB_USERNAME }}/app:${{ github.sha }}
          sleep 5
          curl -s http://127.0.0.1:3000/live | grep live

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: setup build
        uses: docker/setup-buildx-action@v3
      
      - name: Push latest tag
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/app:latest

      - name: Show Docker Hub Link
        run: |
          echo "✅ Docker Hub Repository: https://hub.docker.com/r/${{ vars.DOCKERHUB_USERNAME }}/app"
          echo "🟢 Latest Image Tag: ${{ vars.DOCKERHUB_USERNAME }}/app:latest"
          echo "🟢 Commit Image Tag: ${{ vars.DOCKERHUB_USERNAME }}/app:${{ github.sha }}"
